import { BaseProvider } from "../base.js";
import type {
  ResolvedRule,
  RuleScopeType,
  GeneratedFile,
  ProviderConfig,
  Config,
} from "../../core/schema.js";

export class CopilotProvider extends BaseProvider {
  readonly name = "copilot";
  readonly displayName = "GitHub Copilot";
  readonly defaultOutput = ".github";
  readonly fileExtension = ".md";
  readonly website = "https://github.com/features/copilot";

  generate(
    rules: ResolvedRule[],
    project: Config["project"],
    providerConfig: ProviderConfig
  ): GeneratedFile[] {
    const outputDir = this.getOutputDir(providerConfig);
    const lines: string[] = [];

    lines.push("<!-- Generated by RuleForm — DO NOT EDIT MANUALLY -->");
    lines.push("<!-- Run `ruleform apply` to regenerate -->");
    lines.push("");
    lines.push(`# Copilot Instructions — ${project.name}`);

    if (project.description) {
      lines.push("");
      lines.push(`> ${project.description}`);
    }

    if (project.stack?.length) {
      lines.push("");
      lines.push("## Tech Stack");
      for (const tech of project.stack) {
        lines.push(`- ${tech}`);
      }
    }

    if (project.conventions) {
      lines.push("");
      lines.push("## Conventions");
      if (project.conventions.language)
        lines.push(`- Language: ${project.conventions.language}`);
      if (project.conventions.style)
        lines.push(`- Style: ${project.conventions.style}`);
      if (project.conventions.testing)
        lines.push(`- Testing: ${project.conventions.testing}`);
    }

    // Copilot doesn't support scopes — include all rules
    for (const rule of rules) {
      lines.push("");
      lines.push("---");
      lines.push("");
      lines.push(`## ${rule.description ?? rule.name}`);
      lines.push("");
      lines.push(rule.content);
    }

    lines.push("");

    return [
      {
        path: `${outputDir}/copilot-instructions.md`,
        content: lines.join("\n"),
        provider: this.displayName,
        source: rules.map((r) => r.name),
      },
    ];
  }

  mapScope(scope: RuleScopeType): string {
    // Copilot doesn't support scopes — all rules are always applied
    return "always";
  }
}
