import { BaseProvider } from "../base.js";
import { join } from "node:path";
import type {
  ResolvedRule,
  RuleScopeType,
  GeneratedFile,
  ProviderConfig,
  Config,
} from "../../core/schema.js";

export class GeminiProvider extends BaseProvider {
  readonly name = "gemini";
  readonly displayName = "Gemini Code Assist";
  readonly defaultOutput = ".gemini";
  readonly fileExtension = ".md";
  readonly website = "https://cloud.google.com/gemini";

  generate(
    rules: ResolvedRule[],
    project: Config["project"],
    providerConfig: ProviderConfig
  ): GeneratedFile[] {
    const outputDir = this.getOutputDir(providerConfig);
    const files: GeneratedFile[] = [];

    // Generate style guide markdown files
    const styleGuideDir = join(outputDir, "rules");

    for (const rule of rules) {
      const lines: string[] = [];
      lines.push("<!-- Generated by RuleForm — DO NOT EDIT MANUALLY -->");
      lines.push("");
      lines.push(`# ${rule.description ?? rule.name}`);
      lines.push("");
      const hint = this.scopeHint(rule.scope);
      if (hint) {
        lines.push(`> **Scope:** ${hint}`);
        lines.push("");
      }
      lines.push(rule.content);
      lines.push("");

      files.push({
        path: join(styleGuideDir, `${rule.name}${this.fileExtension}`),
        content: lines.join("\n"),
        provider: this.displayName,
        source: rule.sourceRules,
      });
    }

    // Generate settings.json referencing style guides
    const settings = {
      _generatedBy: "RuleForm — DO NOT EDIT MANUALLY",
      project: {
        name: project.name,
        description: project.description ?? "",
        stack: project.stack ?? [],
      },
      styleGuides: rules.map((r) => ({
        name: r.name,
        description: r.description ?? r.name,
        path: `rules/${r.name}.md`,
      })),
    };

    files.push({
      path: join(outputDir, "settings.json"),
      content: JSON.stringify(settings, null, 2) + "\n",
      provider: this.displayName,
      source: rules.map((r) => r.name),
    });

    return files;
  }

  mapScope(scope: RuleScopeType): string {
    return this.scopeHint(scope);
  }
}
