import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { createTwoFilesPatch } from "diff";
import type { GeneratedFile, PlanResult } from "./schema.js";

const HEADER_MARKER = "Generated by RuleForm";

export function computeDiff(
  generated: GeneratedFile[],
  cwd: string
): PlanResult {
  const created: GeneratedFile[] = [];
  const updated: Array<GeneratedFile & { diff: string }> = [];
  const unchanged: GeneratedFile[] = [];
  const deleted: string[] = [];

  for (const file of generated) {
    const absPath = join(cwd, file.path);

    if (!existsSync(absPath)) {
      created.push(file);
      continue;
    }

    const existing = readFileSync(absPath, "utf-8");
    if (existing.trim() === file.content.trim()) {
      unchanged.push(file);
    } else {
      const diff = createTwoFilesPatch(
        file.path,
        file.path,
        existing,
        file.content,
        "current",
        "ruleform"
      );
      updated.push({ ...file, diff });
    }
  }

  return { created, updated, unchanged, deleted };
}

export function formatPlan(plan: PlanResult): string {
  const lines: string[] = [];

  // Group by provider
  const byProvider = new Map<string, { status: string; path: string; diff?: string }[]>();

  for (const f of plan.created) {
    const group = byProvider.get(f.provider) ?? [];
    group.push({ status: "+", path: f.path });
    byProvider.set(f.provider, group);
  }
  for (const f of plan.updated) {
    const group = byProvider.get(f.provider) ?? [];
    group.push({ status: "~", path: f.path, diff: f.diff });
    byProvider.set(f.provider, group);
  }
  for (const f of plan.unchanged) {
    const group = byProvider.get(f.provider) ?? [];
    group.push({ status: "=", path: f.path });
    byProvider.set(f.provider, group);
  }

  for (const [provider, files] of byProvider) {
    lines.push(`\n  ${provider}:`);
    for (const f of files) {
      const statusLabel =
        f.status === "+"
          ? "CREATE"
          : f.status === "~"
            ? "UPDATE"
            : "UNCHANGED";
      lines.push(`    ${f.status} ${f.path.padEnd(45)} (${statusLabel})`);
    }
  }

  return lines.join("\n");
}

export function isRuleFormGenerated(filePath: string): boolean {
  if (!existsSync(filePath)) return false;
  const content = readFileSync(filePath, "utf-8");
  return content.includes(HEADER_MARKER);
}
