import { writeFileSync, mkdirSync, existsSync, readFileSync, unlinkSync } from "node:fs";
import { join, dirname } from "node:path";
import type { GeneratedFile, ApplyResult } from "./schema.js";

const HEADER_COMMENT = `<!-- Generated by RuleForm — DO NOT EDIT MANUALLY -->
<!-- Run \`ruleform apply\` to regenerate -->`;

const HEADER_MARKER = "Generated by RuleForm";

export function addHeader(content: string, sources: string[]): string {
  const sourceComment = `<!-- Source: ruleform.yaml | Rules: ${sources.join(", ")} -->`;
  return `${HEADER_COMMENT}\n${sourceComment}\n\n${content}`;
}

export async function writeFiles(
  files: GeneratedFile[],
  cwd: string
): Promise<ApplyResult> {
  const written: string[] = [];
  const skipped: string[] = [];
  const errors: Array<{ path: string; error: string }> = [];

  for (const file of files) {
    const absPath = join(cwd, file.path);

    try {
      // Skip if content unchanged
      if (existsSync(absPath)) {
        const existing = readFileSync(absPath, "utf-8");
        if (existing.trim() === file.content.trim()) {
          skipped.push(file.path);
          continue;
        }
      }

      // Create directories
      mkdirSync(dirname(absPath), { recursive: true });

      // Write file
      writeFileSync(absPath, file.content, "utf-8");
      written.push(file.path);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      errors.push({ path: file.path, error: msg });
    }
  }

  return { written, skipped, errors };
}

export function destroyFiles(paths: string[], cwd: string): string[] {
  const removed: string[] = [];

  for (const filePath of paths) {
    const absPath = join(cwd, filePath);
    if (!existsSync(absPath)) continue;

    const content = readFileSync(absPath, "utf-8");
    if (content.includes(HEADER_MARKER)) {
      unlinkSync(absPath);
      removed.push(filePath);
    }
  }

  return removed;
}
