import { describe, it, expect } from "vitest";
import { CursorProvider } from "../../../src/providers/cursor/index.js";
import { ClaudeProvider } from "../../../src/providers/claude/index.js";
import { CopilotProvider } from "../../../src/providers/copilot/index.js";
import { WindsurfProvider } from "../../../src/providers/windsurf/index.js";
import { GeminiProvider } from "../../../src/providers/gemini/index.js";
import type { ResolvedRule, Config } from "../../../src/core/schema.js";

const project: Config["project"] = {
  name: "test-project",
  description: "A test project",
  stack: ["TypeScript", "Next.js"],
  conventions: { language: "TypeScript", style: "functional" },
};

const rules: ResolvedRule[] = [
  {
    name: "general",
    description: "General style",
    scope: "always",
    priority: 1,
    content: "Use functional patterns",
    sourceRules: ["general"],
  },
  {
    name: "api",
    description: "API conventions",
    scope: { globs: ["src/api/**"] },
    priority: 10,
    content: "RESTful only",
    sourceRules: ["api"],
  },
];

const defaultConfig = { enabled: true };

describe("CursorProvider", () => {
  const provider = new CursorProvider();

  it("generates .mdc files per rule + project context", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files.length).toBe(3); // project-context + 2 rules
    expect(files[0].path).toBe(".cursor/rules/project-context.mdc");
    expect(files[1].path).toBe(".cursor/rules/general.mdc");
    expect(files[2].path).toBe(".cursor/rules/api.mdc");
  });

  it("sets alwaysApply for always scope", () => {
    const files = provider.generate(rules, project, defaultConfig);
    const general = files.find((f) => f.path.includes("general"))!;
    expect(general.content).toContain("alwaysApply: true");
  });

  it("sets globs for glob scope", () => {
    const files = provider.generate(rules, project, defaultConfig);
    const api = files.find((f) => f.path.includes("api"))!;
    expect(api.content).toContain("globs:");
    expect(api.content).toContain("src/api/**");
  });

  it("includes RuleForm header", () => {
    const files = provider.generate(rules, project, defaultConfig);
    for (const f of files) {
      expect(f.content).toContain("Generated by RuleForm");
    }
  });
});

describe("ClaudeProvider", () => {
  const provider = new ClaudeProvider();

  it("generates single CLAUDE.md", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files.length).toBe(1);
    expect(files[0].path).toBe("CLAUDE.md");
  });

  it("includes all rules in single file", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files[0].content).toContain("General style");
    expect(files[0].content).toContain("API conventions");
    expect(files[0].content).toContain("Use functional patterns");
    expect(files[0].content).toContain("RESTful only");
  });

  it("includes scope hints", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files[0].content).toContain("Always applied");
  });

  it("includes project info", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files[0].content).toContain("test-project");
    expect(files[0].content).toContain("TypeScript");
    expect(files[0].content).toContain("Next.js");
  });
});

describe("CopilotProvider", () => {
  const provider = new CopilotProvider();

  it("generates copilot-instructions.md in .github", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files.length).toBe(1);
    expect(files[0].path).toBe(".github/copilot-instructions.md");
  });

  it("includes all rules", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files[0].content).toContain("Use functional patterns");
    expect(files[0].content).toContain("RESTful only");
  });
});

describe("WindsurfProvider", () => {
  const provider = new WindsurfProvider();

  it("generates multiple files in .windsurf/rules", () => {
    const files = provider.generate(rules, project, defaultConfig);
    expect(files.length).toBe(3); // project-context + 2 rules
    expect(files[0].path).toContain(".windsurf/rules/");
  });

  it("uses simple markdown without frontmatter", () => {
    const files = provider.generate(rules, project, defaultConfig);
    const general = files.find((f) => f.path.includes("general"))!;
    expect(general.content).not.toContain("---\n");
    expect(general.content).toContain("# General style");
  });
});

describe("GeminiProvider", () => {
  const provider = new GeminiProvider();

  it("generates settings.json + rule files", () => {
    const files = provider.generate(rules, project, defaultConfig);
    const settingsFile = files.find((f) => f.path.includes("settings.json"));
    expect(settingsFile).toBeDefined();
    const ruleFiles = files.filter((f) => f.path.includes("/rules/"));
    expect(ruleFiles.length).toBe(2);
  });

  it("settings.json references style guides", () => {
    const files = provider.generate(rules, project, defaultConfig);
    const settings = files.find((f) => f.path.includes("settings.json"))!;
    const parsed = JSON.parse(settings.content);
    expect(parsed.styleGuides).toHaveLength(2);
    expect(parsed.styleGuides[0].path).toBe("rules/general.md");
  });
});
