import { BaseProvider } from "../base.js";
import { join } from "node:path";
import type {
  ResolvedRule,
  RuleScopeType,
  GeneratedFile,
  ProviderConfig,
  Config,
} from "../../core/schema.js";

export class WindsurfProvider extends BaseProvider {
  readonly name = "windsurf";
  readonly displayName = "Windsurf";
  readonly defaultOutput = ".windsurf/rules";
  readonly fileExtension = ".md";
  readonly website = "https://windsurf.com";

  generate(
    rules: ResolvedRule[],
    project: Config["project"],
    providerConfig: ProviderConfig
  ): GeneratedFile[] {
    const outputDir = this.getOutputDir(providerConfig);
    const files: GeneratedFile[] = [];

    // Project context file
    if (project.stack?.length) {
      const lines: string[] = [];
      lines.push("<!-- Generated by RuleForm — DO NOT EDIT MANUALLY -->");
      lines.push("");
      lines.push(`# Project: ${project.name}`);
      if (project.description) lines.push(`\n> ${project.description}`);
      lines.push("\n## Tech Stack");
      for (const tech of project.stack) lines.push(`- ${tech}`);
      lines.push("");

      files.push({
        path: join(outputDir, `project-context${this.fileExtension}`),
        content: lines.join("\n"),
        provider: this.displayName,
        source: ["project"],
      });
    }

    // One file per rule (Windsurf uses simple markdown, no frontmatter)
    for (const rule of rules) {
      const lines: string[] = [];
      lines.push("<!-- Generated by RuleForm — DO NOT EDIT MANUALLY -->");
      lines.push("");
      lines.push(`# ${rule.description ?? rule.name}`);
      lines.push("");
      const hint = this.scopeHint(rule.scope);
      if (hint) {
        lines.push(`> **Scope:** ${hint}`);
        lines.push("");
      }
      lines.push(rule.content);
      lines.push("");

      files.push({
        path: join(outputDir, `${rule.name}${this.fileExtension}`),
        content: lines.join("\n"),
        provider: this.displayName,
        source: rule.sourceRules,
      });
    }

    return files;
  }

  mapScope(scope: RuleScopeType): string {
    return this.scopeHint(scope);
  }
}
