import { BaseProvider } from "../base.js";
import type {
  ResolvedRule,
  RuleScopeType,
  GeneratedFile,
  ProviderConfig,
  Config,
} from "../../core/schema.js";
import { addHeader } from "../../core/writer.js";
import { join } from "node:path";

export class CursorProvider extends BaseProvider {
  readonly name = "cursor";
  readonly displayName = "Cursor IDE";
  readonly defaultOutput = ".cursor/rules";
  readonly fileExtension = ".mdc";
  readonly website = "https://cursor.com";

  generate(
    rules: ResolvedRule[],
    project: Config["project"],
    providerConfig: ProviderConfig
  ): GeneratedFile[] {
    const outputDir = this.getOutputDir(providerConfig);
    const files: GeneratedFile[] = [];

    // Generate project context rule
    const projectContent = this.buildProjectContext(project);
    if (projectContent) {
      files.push({
        path: join(outputDir, `project-context${this.fileExtension}`),
        content: this.buildMdc(
          "Project context and tech stack",
          "always",
          undefined,
          projectContent
        ),
        provider: this.displayName,
        source: ["project"],
      });
    }

    // Generate one .mdc file per rule
    for (const rule of rules) {
      const frontmatter = this.buildFrontmatter(rule);
      const content = this.buildMdc(
        rule.description ?? rule.name,
        rule.scope,
        typeof rule.scope === "object" && "globs" in rule.scope
          ? rule.scope.globs
          : undefined,
        rule.content
      );

      files.push({
        path: join(outputDir, `${rule.name}${this.fileExtension}`),
        content,
        provider: this.displayName,
        source: rule.sourceRules,
      });
    }

    return files;
  }

  mapScope(scope: RuleScopeType): string {
    if (scope === "always") return "alwaysApply: true";
    if (scope === "agent-requested") return "alwaysApply: false";
    if (scope === "manual") return "alwaysApply: false";
    if (typeof scope === "object" && "globs" in scope) {
      return `globs: ${JSON.stringify(scope.globs)}`;
    }
    return "alwaysApply: false";
  }

  private buildMdc(
    description: string,
    scope: RuleScopeType,
    globs: string[] | undefined,
    content: string
  ): string {
    const lines: string[] = ["---"];
    lines.push(`description: ${description}`);

    if (scope === "always") {
      lines.push("alwaysApply: true");
    } else if (globs && globs.length > 0) {
      lines.push(`globs: ${JSON.stringify(globs)}`);
    } else {
      lines.push("alwaysApply: false");
    }

    lines.push("---");
    lines.push("");
    lines.push(`<!-- Generated by RuleForm — DO NOT EDIT MANUALLY -->`);
    lines.push("");
    lines.push(content);

    return lines.join("\n");
  }

  private buildFrontmatter(rule: ResolvedRule): string {
    return this.mapScope(rule.scope);
  }

  private buildProjectContext(project: Config["project"]): string | null {
    if (!project.stack?.length) return null;

    const lines: string[] = [];
    lines.push(`# Project: ${project.name}`);
    if (project.description) lines.push(`\n> ${project.description}`);
    lines.push("\n## Tech Stack");
    for (const tech of project.stack) {
      lines.push(`- ${tech}`);
    }
    if (project.conventions) {
      lines.push("\n## Conventions");
      if (project.conventions.language)
        lines.push(`- Language: ${project.conventions.language}`);
      if (project.conventions.style)
        lines.push(`- Style: ${project.conventions.style}`);
      if (project.conventions.testing)
        lines.push(`- Testing: ${project.conventions.testing}`);
    }
    return lines.join("\n");
  }
}
